#page title
page_title                                : Surf Report & Swell Buoys by Buoywatch app      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1479691525                                     # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                                # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                                # Enter Google Play Store URL.
presskit_download_link                    : https://buoywatch.com/assets/press_kit.zip     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                           # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Get notified when surfing is good—with wave size alerts. NOAA buoy readings & surf forecast in real-time.

enable_apple_watch                        : true                                           # Set to true to display an apple watch app image.
enable_smart_app_banner                   : true                                           # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Pablo & Raf                              
your_link                                 : https://twitter.com/ppacie            
your_city                                 :                               
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : ppacie
github_username                           : ppacie
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Live Buoy Weather
    description                           : It includes wave size, swell direction and swell period. Some buoys provide weather information, such as wind direction, wind speed, pressure, air and water temperature.
    fontawesome_icon_name                 : water
    
  - title                                 : iPhone and Apple Watch
    description                           : Support for iPhone and Apple Watch devices. More to come in the future.
    fontawesome_icon_name                 : laptop-code
    
  - title                                 : Notifications
    description                           : Score the best surf with Notifications. Get alerted when the swell is above a specific wave height. Includes animated GIFs.
    fontawesome_icon_name                 : bell
    
  - title                                 : Widgets
    description                           : Swell and wind information at a glance. Always easily accesible and customizable. Support for Home, Lock screen and Stand by mode iOS Widgets. 
    fontawesome_icon_name                 : star

  - title                                 : Complications
    description                           : Support for Graphic, Modular and Circular Apple Watch Complications. Get real-time wave data displayed at a glance.
    fontawesome_icon_name                 : clock
    
  - title                                 : Theme selection
    description                           : Select between dark, light or automatic matching system appearance.
    fontawesome_icon_name                 : adjust

  - title                                 : Historic Data Chart
    description                           : 24-hour charts data. Including time, wave size and swell period.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Offline Mode Support
    description                           : If offline, lastly marine buoys observations will always be available for your main buoy.
    fontawesome_icon_name                 : unlink

  - title                                 : Covered Areas
    description                           : North America (Washington to California, Main to Florida, Alaska, US Virgin Islands, Puerto Rico, US/Canada Great Lakes, Gulf of Mexico), Hawaii, Australia, Europe, Caribbean, Samoa, Guam, Azores.
    fontawesome_icon_name                 : map-marked-alt

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/jp-fichman-unsplash.jpg            # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.
watch_color                               : black                                     # Set to: black or white.

body_background_color                     : "#1c1c1e"

link_color                                : '#ff4331' #"#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#666666"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
